### ISSUE TITLE
Feature request: Add autocomplete color for all themes

### ISSUE THREAD

**Issue by florisbosch** [ankarhem/tailwind-easy-theme#2]
It would be great if we could add a suffix to all theme colors so that we can easily see the differences between similar colors when autocompleting.

For example, we could add "-light" or "-dark" to the end of each color name to show which theme it belongs to.

This will only be to make it easy to check to colors during development, you won't choose these as classes only for lookup

**Comment by ankarhem** [comment]
This is an interesting idea. I do not like this particular solution to viewing the variants' colors though. Since adding "fake" classes wouldn't be intuitive.

Currently the intellisense can show the colors for the primary theme, since the tailwind configuration is initialized as 
```
primary-100: hsl(var(--color-primary-100, <primary_color_as_hex_value>) / <tailwind opacity value>)
```

The important part is that since vscode, which in a sense a browser, doesn't have the stylesheet which declares the css variables, it cannot evaluate the css variables and therefore not show a preview for the color.

This is solved by converting the primary themes color to a hex value in the `var()` to the second parameter `<primary_color_as_hex_value>`, which is a fallback value. This will always be picked because of the reason above.

Maybe it could be solved by creating a vscode plugin that can filter the output tailwind css and inject it, and therefore have access to the css variables and allowing you to toggle between the primary / variant themes, however I don't know if this complexity would offer any meaningful value over simply selecting the theme in the app you're developing.
